### ISSUE TITLE
Looking for RL algorithm implementation

### ISSUE THREAD

**Issue by chenziku** [openai/summarize-from-feedback#1]
It seems that the training calls sup4_ppo_rm4 fine-tuner, which loads from a link. Is there specific implementations of these fine-tuners with the RL algorithm (PPO's KL and value net etc.)?

**Comment by daniel-ziegler** [comment]
Unfortunately our training code relied on too much internal infrastructure so we were not able to release it at this time. You can find a TensorFlow implementation of fine-tuning NLP models with RL in our previous release here: https://github.com/openai/lm-human-preferences
