### ISSUE TITLE
`openaipublic.blob.core.windows.net` has a broken CDN

### ISSUE THREAD

**Issue by JoeyBlogs** [openai/summarize-from-feedback#17]
When loading `favicon.ico` and any dataset I get:
```xml
<Error>
<Code>OutOfRangeInput</Code>
<Message>One of the request inputs is out of range. RequestId:9d071783-801e-006d-71aa-9d6884000000 Time:2022-07-22T09:04:31.8323083Z</Message>
</Error>
```

Do you get the same? https://openaipublic.blob.core.windows.net/summarize_from_feedback/datasets/tldr_3_filtered

**Comment by longouyang** [comment]
Apologies for the delay - the readme had incorrect links to the dataset files.

I've updated the readme and also included the links here:

https://openaipublic.blob.core.windows.net/summarize-from-feedback/datasets/tldr_3_filtered/train.jsonl https://openaipublic.blob.core.windows.net/summarize-from-feedback/datasets/tldr_3_filtered/valid.jsonl https://openaipublic.blob.core.windows.net/summarize-from-feedback/datasets/tldr_3_filtered/test.jsonl https://openaipublic.blob.core.windows.net/summarize-from-feedback/datasets/tldr_3_filtered/samples.txt
