### ISSUE TITLE
Use which part of dataset to finetune model?

### ISSUE THREAD

**Issue by xuyifan-0731** [openai/summarize-from-feedback#18]
Hi, thanks for your great work.! In you paper part 3.1 said that ` We start with an initial policy that is fine-tuned via supervised learning on the desired dataset (in our case, the Reddit TL;DR summarization dataset). ` 
Which part of the dataset was used for this step of pre training? Is it a train set, that is, batch 3-10 and 15 in the data you provide? And whether all two results of each group are used in this step of training?

**Comment by longouyang** [comment]
Note that we filtered the original dataset a bit for our supervised learning finetunes - see this [section of the README for details](https://github.com/openai/summarize-from-feedback#reddit-tldr-dataset)
