### ISSUE TITLE
cuda runtime error (101) : invalid device ordinal

### ISSUE THREAD

**Issue by ioannist** [openai/summarize-from-feedback#5]
The evaluation was successful, however, the tests failed. I have an Nvidia 1080Ti and CUDA_VISIBLE_DEVICES=0. Perhaps your code is looking for multiple GPUs?

```
  File "/home/ioannis/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 292, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /pytorch/torch/csrc/cuda/Module.cpp:59
```

**Comment by daniel-ziegler** [comment]
Yep, sorry about that; by default the tests were using 2-4 GPUs. I just pushed an update that switches them to use 1 GPU by default, which seems better.

**Comment by ioannist** [comment]
thanks!
