### ISSUE TITLE
How to assign rewards to each time step in a generation trajectory?

### ISSUE THREAD

**Issue by ArvinZhuang** [openai/summarize-from-feedback#6]
Hi, from the paper, it seems that we only get an estimated reward at the end of the generation episode.
Then how do we assign the final reward to each action in the episode trajectory? I mean could you tell me what hyperparameters for PPO you were using in the experiments? or is there anything I misunderstand?
Thanks!

**Comment by daniel-ziegler** [comment]
Like any RL algorithm, PPO takes care of the credit assignment problem for us, figuring out which actions to upweight and downweight. That means it's fine for us to only apply the estimated reward at the end of the episode. (The KL penalty is applied at each token.)

We used gamma = 1 and lambda = 0.95 as hyperparameters for GAE, if that's what you're wondering. (You can find other hyperparameters in Appendix B1 in our paper: https://arxiv.org/pdf/2009.01325.pdf.)

**Comment by ArvinZhuang** [comment]
Thank you so much!

**Comment by sinhprous** [comment]
Hello @daniel-ziegler, as I understand, the GAE is simply weighted combination of n-step returns. 
![image](https://user-images.githubusercontent.com/22270984/113657055-57c33000-96c7-11eb-9175-d365c267ab7b.png)
But we only have estimated reward at the end of the episode. So GAE in this implementation is just a term A^{pi}_n where n is the length of the input sequence (not summing over n), right?

**Comment by daniel-ziegler** [comment]
No, we also give rewards at each timestep for the KL penalty. Our episodes always fit in a single rollout though so the final term does fall away.

**Comment by sinhprous** [comment]
Sorry to bother you @daniel-ziegler, I don't understand it clearly. So could you describe more detail about the reward at each timestep? I mean the exact formula for `r(s_t, a_t)`

**Comment by sinhprous** [comment]
`Note that the reward model only gives rewards for entire summaries, and not at intermediate time steps. In
RL terminology, each episode terminates when the policy outputs the EOS token, and the discount factor γ = 1.`
Oh I had missed this part in the paper. So my understanding is that at each intermediate step, the reward contains only the KL penalty term, and at the final step, the reward is the sum of KL penalty term and the output of reward model, right?

**Comment by sinhprous** [comment]
`Note that the reward model only gives rewards for entire summaries, and not at intermediate time steps. In RL terminology, each episode terminates when the policy outputs the EOS token, and the discount factor γ = 1.`
Oh sorry @daniel-ziegler, I had missed this part in the paper. So my understanding is that at each intermediate step, the reward contains only the KL penalty term, and at the final step, the reward is the sum of KL penalty term and the output of reward model, right?

**Comment by daniel-ziegler** [comment]
That is correct.
