### ISSUE TITLE
License for dataset?

### ISSUE THREAD

**Issue by AdamGleave** [openai/summarize-from-feedback#8]
Hi,

Could you clarify what license the dataset is released under? The [LICENSE](https://github.com/openai/summarize-from-feedback/blob/master/LICENSE) file in the repo says "Software Copyright (c) 2020 OpenAI" so I'm not sure if it's intended to cover the dataset or only the source code.

Thanks!

@daniel-ziegler

**Comment by daniel-ziegler** [comment]
Hi Adam!

The license is intended to apply to our feedback dataset as well; I've added some language to clarify. (It doesn't apply to our copy of the TL;DR dataset, of course.) Feel free to use the data as you see fit!

**Comment by AdamGleave** [comment]
Thanks for updating the license to clarify :)
